# Site settings
title: ロジカルオシレーターOfficial Homepage
email: logicaloscillator@gmail.com
description: >
  都内で活動する、女性ボーカルバンド　「ロジカルオシレーター」　です。

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://logical-oscillator.github.io/"
twitter_username: logical-oscillator
github_username: logical-oscillator
mirror_ga_tracking_id: "UA-58426382-2"
production_ga_tracking_id: "UA-58426382-1"

# Build settings
markdown: kramdown
